# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install linux dependencies
      run: sudo apt-get update -y && sudo apt-get install -y clamav clamav-daemon
      
    - name: ClamAV setup
      run: sudo sed -i 's/^\(LocalSocketGroup\s*\).*$/\1root/' /etc/clamav/clamd.conf
      
    - name: ClamAV set user
      run: sudo sed -i 's/^\(User\s*\).*$/\1root/' /etc/clamav/clamd.conf
            
    - name: ClamAV restart freshclam
      run: sudo systemctl restart clamav-freshclam.service
      
    - name: ClamAV restart
      run: sudo systemctl start clamav-daemon.service
      
    - name: Check ClamAV is-active
      run: systemctl status clamav-daemon.service
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
      
    - name: Build
      run: go build -v -o=example/example example/*.go
      
    - name: Test
      run: go test -v ./...
